### ISSUE TITLE
Speed up topic fetching by running requests in parallel

### ISSUE THREAD

**Issue by GreyKn** [devshawn/kafka-gitops#16]
I have a kafka server with >100 topics. State appears to be fetched from Kafka serially, so a plan takes 3+ minutes.

**Comment by devshawn** [comment]
I agree. I believe this is because we fetch topic configurations for each topic one-by-one.

**Comment by devshawn** [comment]
Hey @GreyKn, feel free to give [0.2.5](https://github.com/devshawn/kafka-gitops/releases/tag/0.2.5) a try. From my initial testing, the `plan` process has significantly improved.
