### ISSUE TITLE
Possible to use this against an existing cluster and not destroy it?

### ISSUE THREAD

**Issue by jurschel** [devshawn/kafka-gitops#31]
So given that we have existing clusters is it even possible to use the tool just to create topics?

**Comment by devshawn** [comment]
Yes, you can use the tool to just create new topics. You can run `kafka-gitops` with the `--no-delete` flag, and it will only plan/apply creates and updates. 

Example state file `new-topics.yaml`:

```yaml
topics:
  my-new-topic:
    partitions: 6
    replication: 3
```

Run against the cluster:

```bash
kafka-gitops -f new-topics.yaml --no-delete plan -o plan.json
kafka-gitops -f new-topics.yaml --no-delete apply -p plan.json
```

Over time, you can slowly start to add existing topics (and services, if desired) to your state file until we have implemented import functionality (#13).

**Comment by jurschel** [comment]
Ah ok thanks for the response.  I was about to reply with the below.  I did see something about the --no-delete option just hadn't gotten to it yet.

I see in your documentation that applying this against a cluster is destructive if you don't have all the topics in the state file.  Shouldn't you leave any built-in topics like _confluent.support.metrics, _confluent_offsets and _schemas alone completely?

**Comment by jurschel** [comment]
That worked.  Good work.  Now I'm going to get my central repository for topics going!

**Comment by devshawn** [comment]
Glad to hear that worked, @jurschel! 

It would probably be a good idea to completely ignore those specific topics, but we've chosen so far to just define them as-is in our state file. 

You can also use the topic blacklist option to have the tool ignore topics on a prefixed basis:

```yaml
settings:
  topics:
    blacklist:
      prefixed:
        - _confluent
```

Good luck with getting your central repository going! Let me know if you have questions! 😄
