### ISSUE TITLE
Double quotes in passwords are not escaped

### ISSUE THREAD

**Issue by erikhh** [devshawn/kafka-gitops#43]
First of all, thank you for creating this wonderful piece of kit! It is ridiculously useful.

We're using SASL-SCRAM login on our Kafka, but looking at the code this issue would be applicable to all JAAS usernames and passwords.
Our passwords are randomly generated and occasionally contain double quote characters (`"`). The config for the gitops user looks somewhat like this:

```
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="my-gitops-user" password="XXXXXXXXX"YYYYY";
```

Then when running 'kafka-gitops plan` it gives this error:
```
[ERROR] Error thrown when creating Kafka admin client:
Value not specified for key 'YYYYY' in JAAS config
```

I had a look at the code. And it looks easy enough to fix. I'll submit a PR for this later tonight if that's ok with you.

**Comment by devshawn** [comment]
Thanks @erikhh, I'm happy you are a fan of the tool! I've merged your PR and released it in `0.2.13`.
