### ISSUE TITLE
Idempotency issue

### ISSUE THREAD

**Issue by swapnilborade** [devshawn/kafka-gitops#49]
For some topics , we are facing idempotency issue. It creates topic first time but during second run we get below issue.

I am not able to reproduce similar issue on other kafka cluster.

./kafka-gitops -v -f new.yml --no-delete apply
Executing apply...

03:39:06.846 [main] INFO com.devshawn.kafka.gitops.config.KafkaGitopsConfigLoader - Kafka Config: {bootstrap.servers=localhost:9092, client.id=kafka-gitops}
03:39:06.853 [main] INFO com.devshawn.kafka.gitops.service.ParserService - Parsing desired state file...
03:39:07.606 [main] INFO com.devshawn.kafka.gitops.manager.PlanManager - [PLAN] Topic test-OWN-0 does not exist; it will be created.
Applying: [CREATE]

+ [TOPIC] test-OWN-0
        + partitions: 6
        + replication: 1
        + configs:
                + cleanup.policy: compact

[ERROR] Error thrown when attempting to create a Kafka topic:
org.apache.kafka.common.errors.TopicExistsException: Topic 'test-OWN-0' already exists.

[ERROR] An error has occurred during the apply process.
[ERROR] The apply process has stopped in place. There is no rollback.
[ERROR] Fix the error, re-create a plan, and apply the new plan to continue.

**Comment by devshawn** [comment]
Hi @swapnilborade,

Without more information, I'm not sure I have much advice to offer. Do you have security on this cluster? My first guess would be the permissions for the user running `kafka-gitops` does not have the correct ACLs. This could make it so when we fetch the list of topics for the cluster, we do not get all of them, thus, kafka-gitops would try to re-create a topic that already exists.

See the documentation for the required ACLs for kafka-gitops here: https://devshawn.github.io/kafka-gitops/#/permissions?id=state-file-definition

If it's not permissions related, I think we'd need to know more about your setup and try to reproduce it.

**Comment by devshawn** [comment]
It may help to run `plan` and `apply` separately and output the plan as a file to investigate further.

**Comment by danielprinz** [comment]
Thanks. Had a similar issue. Applying the correct permissions of the git-ops user solved it 🎉 => [doc](https://devshawn.github.io/kafka-gitops/#/permissions?id=state-file-definition)

**Comment by devshawn** [comment]
@swapnilborade Let me know if you are still seeing issues after looking into the permissions for your gitops user. Thanks!
