### ISSUE TITLE
plan error

### ISSUE THREAD

**Issue by sunny092318** [devshawn/kafka-gitops#78]
I am trying to setup the kafka-gitops for my project. We have four kafka broker as per below, once I setup the environment variables export KAFKA_BOOTSTRAP_SERVERS=xxxx.xxxx.xxx.xxx.example.org:9092 on my jump box. Then executing the plan, getting the below error.

## kafka-gitops -v  plan
Generating execution plan...
 
11:03:51.023 [main] INFO com.devshawn.kafka.gitops.config.KafkaGitopsConfigLoader - Kafka Config: {bootstrap.servers=xxxx.xxxx.xxx.xxx.example.org:9092, client.id=kafka-gitops}
11:03:51.027 [main] INFO com.devshawn.kafka.gitops.service.ConfluentCloudService - Using ccloud executable at: ccloud
11:03:51.028 [main] INFO com.devshawn.kafka.gitops.service.ParserService - Parsing desired state file...
[ERROR] Error thrown when attempting to list Kafka topics:
org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
 
[ERROR] An error has occurred during the planning process. No plan was created.

**Comment by devshawn** [comment]
Hi @sunny092318, this timeout usually happens if you have not set credentials. You likely need to set more than just your bootstrap servers.

**Comment by sunny092318** [comment]
@devshawn Thanks for providing assistance. Trying to setup kakfa-gitops for on-premises kafka cluster consist of multiple broker which has GSSAPI Kerberos enabled environment. I do pass below parameter as environment variables but unable to connect to kafka broker. Does current version of kafka-gitops support GSSAPI Kerberos authentication.

====
kafka-gitops -v --no-delete plan
Generating execution plan...

09:31:55.286 [main] INFO com.devshawn.kafka.gitops.config.KafkaGitopsConfigLoader - Kafka Config: {command.config=/home/local/client.properties, keytab=/home/local/abc.keytab, ssl.keystore.location=/home/local/abc_keystore.jks, bootstrap.servers=kfk0001.t006.tpc.tgrc.tesco.org:9092,kfk0002.t006.tpc.tgrc.tesco.org:9092,kfk0003.t006.tpc.tgrc.tesco.org:9092,kfk0004.t006.tpc.tgrc.tesco.org:9092, sasl.kerberos.service.name=abc, security.protocol=SASL_SSL, principal=abc, ssl.truststore.location=/home/local/wild_truststore.jks, ssl.keystore.password=changeit, opts=-Djava.security.auth.login.config=/home/local/kafka_client_jaas.conf -Dsun.security.krb5.debug=true, sasl.mechanism=GSSAPI, ssl.key.password=changeit, ssl.truststore.password=changeit, client.id=kafka-gitops}
09:31:55.290 [main] INFO com.devshawn.kafka.gitops.service.ConfluentCloudService - Using ccloud executable at: ccloud
09:31:55.292 [main] INFO com.devshawn.kafka.gitops.service.ParserService - Parsing desired state file...
[ERROR] Error thrown when creating Kafka admin client:
Could not find a 'KafkaClient' entry in the JAAS configuration. System property 'java.security.auth.login.config' is not set

[ERROR] An error has occurred during the planning process. No plan was created.
====

**Comment by sunny092318** [comment]
@devshawn Thanks for providing assistance. Trying to setup kakfa-gitops for on-premises kafka cluster consist of multiple broker which has GSSAPI Kerberos enabled environment. I do pass below parameter as environment variables but unable to connect to kafka broker. Does current version of kafka-gitops support GSSAPI Kerberos authentication.

====
kafka-gitops -v --no-delete plan
Generating execution plan...

09:31:55.286 [main] INFO com.devshawn.kafka.gitops.config.KafkaGitopsConfigLoader - Kafka Config: {command.config=/home/local/client.properties, keytab=/home/local/abc.keytab, ssl.keystore.location=/home/local/abc_keystore.jks, bootstrap.servers=abc1:9092,abc2:9092,abc3:9092,abc4:9092, sasl.kerberos.service.name=abc, security.protocol=SASL_SSL, principal=abc, ssl.truststore.location=/home/local/wild_truststore.jks, ssl.keystore.password=changeit, opts=-Djava.security.auth.login.config=/home/local/kafka_client_jaas.conf -Dsun.security.krb5.debug=true, sasl.mechanism=GSSAPI, ssl.key.password=changeit, ssl.truststore.password=changeit, client.id=kafka-gitops}
09:31:55.290 [main] INFO com.devshawn.kafka.gitops.service.ConfluentCloudService - Using ccloud executable at: ccloud
09:31:55.292 [main] INFO com.devshawn.kafka.gitops.service.ParserService - Parsing desired state file...
[ERROR] Error thrown when creating Kafka admin client:
Could not find a 'KafkaClient' entry in the JAAS configuration. System property 'java.security.auth.login.config' is not set

[ERROR] An error has occurred during the planning process. No plan was created.

**Comment by sunny092318** [comment]
Got resolved ..
